name: Build, Test, and Push Docker image

on:
  push:
    branches:
      - main 

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # This job must complete in 10 minutes or less

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven and run tests
      run: mvn clean test
#      run: mvn clean package
#
#    - name: Log in to GitHub Container Registry
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.CR_PAT }}
#
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        file: ./Dockerfile
#        push: true
#        tags: ghcr.io/${{ github.repository_owner }}/shoppings:latest
